#! /usr/bin/ruby
# tac utility (reverse of cat)
# This is available on Linux, 
# providing for Mac environment
# Outputs a file with lines in reverse order

fname = ARGV[0]
f = File.open(fname, 'r')
lines = []
f.each { |l| lines << l }
lines.reverse!
lines.each { |l| puts l }
