# ------------------------------------------------------------------------------
# This file contains all of the error messages the system can send to the client
#
# This and all other YAML files in the ./config directory will be reloaded by the Delivery Aggregator as soon as you save your
# changes. This means that once you add a service here, it will be available to the next incoming request (The Aggregator will
# not dispatch to the new service(s) though until after you add it them to the rules.yaml)
#
# Because the system will auto reload this file make sure that there are no <tab> characters before you save. Tab characters
# break the YAML parser and will cause the Aggregator to shutdown!
# ------------------------------------------------------------------------------

# Controller
generic_http_error: "? encountered an error!"

# Item
undefined_item_type: '? is either an unknown data type or you did not supply the ./config/data.yaml configuration file!'

# Translator
missing_translator_mapping_file: 'The translator mapping file specified, ?, could not be found in ./config/'

#Broker
broker_no_services_available: 'No services could fulfill your request.'
broker_bad_item_message: 'Invalid citation genre and/or content_type'
broker_response_success: 'All services have responded.'

# Tier 
tier_not_a_service: '? is not a valid service!'
tier_no_original_item: 'The original citation is undefined!'
tier_unknown_item_type: 'The information returned from ? could not be processed!'
tier_timeout: 'Tier ? timed out while contacting its services!'

# Service
service_no_name: 'Your service must have a name!'
service_no_target_defined: Cannot contact ? because no HTTP target is defined in ./config/services.yaml!'
service_connection_refused: 'The ? service appears to be offline!'
service_wrong_response: 'The response from ? could not be verified.'
service_timeout: '? took too long to respond.'
service_bad_request: 'The JSON sent to ? appears to have been invalid!'
service_bad_json: '? did not return valid JSON.'
service_unknown_item: '? returned an unknown item type.'
service_server_error: '? was unable to process the request.'
service_server_error_fatal: 'The ? service could not respond to your request.'
service_buffer_overflow: 'The response from ? was too large!'

# Consortial Affiliation Service
consortial_error: 'Unable to determine the affiliation of the client do to an error!'
consortial_too_large: 'Response from the consortial service was too large!'