# ------------------------------------------------------------------------------
# This file contains all of the error messages the system can send to the client
#
# This and all other YAML files in the ./config directory will be reloaded by the Delivery Aggregator as soon as you save your
# changes. This means that once you add a service here, it will be available to the next incoming request (The Aggregator will
# not dispatch to the new service(s) though until after you add it them to the rules.yaml)
#
# Because the system will auto reload this file make sure that there are no <tab> characters before you save. Tab characters
# break the YAML parser and will cause the Aggregator to shutdown!
# ------------------------------------------------------------------------------

# Item
undefined_item_type: '? is either an unknown data type or you did not supply the ./config/data.yaml configuration file!'

# Translator
missing_translator_mapping_file: 'The translator mapping file specified, ?, could not be found in ./config/'

#Broker
broker_no_services_available: 'No services could fulfill your request.'
broker_bad_item_message: 'Invalid citation genre and/or content_type'
broker_response_holding_remain: 'Not enough citation information to process remaining services.'
broker_response_errored: 'Unable to complete request.'
broker_response_success: 'All services have responded.'

# Tier 
tier_no_name: 'The tier must have a name!'
tier_not_a_service: '? is not a valid service!'
tier_no_original_item: 'The original citation is undefined!'
tier_unknown_item_type: 'The information returned from ? could not be processed!'
tier_services_not_array: 'The services for tier ? must be an Array!'
tier_services_no_services: 'Each service for tier ? must be an instance of a Service!'
tier_unable_to_process_results: 'Unable to process the results from ?!'
tier_timeout: 'Tier ? timed out while contacting its services!'

# Service
service_not_found: '? did not find any results.'
service_no_name: 'Your service must have a name!'
service_no_target_defined: Cannot contact ? because no HTTP target is defined in ./config/services.yaml!'
service_connection_refused: 'The ? service appears to be offline!'
service_wrong_response: 'The response from ? could not be verified.'
service_timeout: '? took too long to respond.'
service_bad_request: 'The JSON sent to ? appears to have been invalid!'
service_bad_json: '? did not return valid JSON.'
service_unknown_item: '? returned an unknown item type.'
service_unable_to_translate: 'Unable to interpret the response from ?'
service_server_error: '? was unable to process the request.'
service_server_error_fatal: 'The ? service could not respond to your request.'
service_buffer_overflow: 'The response from ? was too large!'

# General
bad_url: 'Invalid URL!'
bad_boolean: 'Must be a boolean value!'





# -------------------------------------------------------------------
# Citation Object Specific
bad_genre: 'Invalid genre!'
bad_content_type: 'Invalid content type!'

# -------------------------------------------------------------------
# Resource Object Specific
bad_format: 'Format must be a ResourceFormat!'

# -------------------------------------------------------------------
# Citation Augmentation Specific
#    will replace the question mark with: method
augmentation: 'Unable to augment the citation for ?!'
#    will replace the question mark with: author.to_s 
author_augmentation: "Unable to attach ? to the citation!"
#    will replace the question mark with: resource.to_s 
resource_augmentation: 'Unable to attach ? to the citation!'


# -------------------------------------------------------------------
# Core object errors
incomplete_citation: 'Your citation does not contain a genre and/or content type!'
#    will replace the question mark with: service.name 
generic_broker_error: 'An error occurred while sending your request to ?.'

# -------------------------------------------------------------------
# Service errors
#    will replace the question mark with: service.name
generic_http_error: "? encountered an error!"
#    will replace the question mark with: service.name
http_bad_uri: "Invalid URI in request to ?!"
#    will replace the question mark with: service.name
http_timeout: 'Request sent to ? timed out!'
#    will replace the question mark with: http status code
http_status: '? responded with an invalid HTTP code: ?'
#    will replace the question marks with: service.name
http_no_response: '? never responded!'
#    will replace the question mark with: service.name
missing_service_config: 'No configuration file could be found for ?!'
#    will replace the question mark with: service.name
missing_base_url: 'No Url was defined for ?!'
missing_name: 'No name was provided for the service!'