# This service uses the nodemailer module. Please refer to it for information on setting up
# your transport information 
# Leave these blank if you will be sending mail directly from the server over port 25
service: ''
username: ''
password: ''

from: 'cdla-dev@ucop.edu'
to: 'brian.riley@ucop.edu; joe.ferrie@ucop.edu; stephanie.collett@ucop.edu'
subject: 'Cedilla has encountered a potentially fatal error!'